import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../componants/Header";
import Navbar from "@/componants/Navbar";
import Footer from "@/componants/Footer";
import { CartProvider } from "@/context/CartContext";
import { WishlistProvider } from "@/context/WishlistContext";
import { AppProvider } from "@/context/appcontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
        <WishlistProvider>
          <CartProvider>
            {children}
          </CartProvider>
        </WishlistProvider>
        </AppProvider>
      </body>
    </html>
  );
}
