import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "../../componants/Header";
import Navbar from "../../componants/Navbar";
import Footer from "../../componants/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
